### ISSUE TITLE
"TypeError: matcherResult.message is not a function" after upgrade jest to latest version (27.0.3)

### ISSUE THREAD

**Issue by alexneo2003** [mattphillips/jest-expect-message#39]
**Bug**

"TypeError: matcherResult.message is not a function" exception after upgrade jest to latest version (27.0.3)

npx envinfo --preset jest

  System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 14.16.0
    Yarn: 1.22.5
    npm: 6.14.11
  npmPackages:
    jest: ^27.0.3 => 27.0.3
    jest-expect-message: 1.0.2

**Relevant code or config**

```javascript
module.exports = {
  preset: 'ts-jest',
  reporters: [
    'default',
    'jest-html-reporters',
  ],
  runner: 'groups',
  setupFilesAfterEnv: ['jest-expect-message'],
};


```

**What you did:**
upgrade jest to latest version 27.0.3

What happened (please provide anything you think will help):
when expect was failed instead receive custom message with error text i'm receive exception:
```javascript 
TypeError: matcherResult.message is not a function
```

Reproduction repository (if possible):
yarn install jest@27.0.3

```javascript
expect(false, "false can't be true").toBe(true);
```

**Comment by alexneo2003** [comment]
i'm published package @alex_neo/jest-expect-message
check pls
connect to project as 
```javascript
  setupFilesAfterEnv: ['@alex_neo/jest-expect-message'],
```

**Comment by adrian-kriegel** [comment]
downgrading to jest@26.6.3 fixes the issue for now

**Comment by goldfita** [comment]
I am also getting this message on Jest 27.1.0.

**Comment by alexneo2003** [comment]
> I am also getting this message on Jest 27.1.0.

https://github.com/mattphillips/jest-expect-message/issues/39#issuecomment-865691968

**Comment by pete-hotchkiss** [comment]
I've been puzzled by this since upgrading to `27.x.y` so have eventually given in and raised a ticket on the Jest repos

https://github.com/facebook/jest/issues/11933

**Comment by bennycode** [comment]
@alexneo2003 can you please contribute your code to the main package here? @mattphillips are you looking into this problem?

**Comment by alexneo2003** [comment]
> @alexneo2003 can you please contribute your code to the main package here? @mattphillips are you looking into this problem?

Check this [comment](https://github.com/mattphillips/jest-expect-message/issues/39#issuecomment-865691968)

**Comment by denyo** [comment]
> @alexneo2003 can you please contribute your code to the main package here? @mattphillips are you looking into this problem?

The PR is open for like 4 months: https://github.com/mattphillips/jest-expect-message/pull/40

**Comment by alexn-s** [comment]
still getting the issue

**Comment by alexneo2003** [comment]
> package @alex_neo/jest-expect-message check pls connect to project as
> 
> ```js
>   setupFilesAfterEnv: ['@alex_neo/jest-expect-message'],
> ```

try modified package `@alex_neo/jest-expect-message`
connect to project as

``` javascript
 setupFilesAfterEnv: ['@alex_neo/jest-expect-message'],
```

**Comment by nicolasturcksin** [comment]
Hi,

First Thanks for the Job 👍 , but seems that this version is not publish on npm (I'm maybe wrong), in case I'm right would it be possible to publish the last version ?

Thanks!

**Comment by alexneo2003** [comment]
> Hi,
> 
> First Thanks for the Job 👍 , but seems that this version is not publish on npm (I'm maybe wrong), in case I'm right would it be possible to publish the last version ?
> 
> Thanks!


try modified package `@alex_neo/jest-expect-message`
connect to project as

``` javascript
 setupFilesAfterEnv: ['@alex_neo/jest-expect-message'],
```

**Comment by nicolasturcksin** [comment]
Yep works, is this project dead ? 

Thanks !

**Comment by alexneo2003** [comment]
rather yes than no

> Yep works, is this project dead ?
> 
> Thanks !

rather yes than no

**Comment by alexneo2003** [comment]
modified package `@alex_neo/jest-expect-message`
connect to project as

``` javascript
 setupFilesAfterEnv: ['@alex_neo/jest-expect-message'],
```

**Comment by mattphillips** [comment]
Sorry for the delay in coming to this!!! I've just published a new version with the fix for this in: https://www.npmjs.com/package/jest-expect-message/v/1.0.4

**Comment by bennycode** [comment]
Better a year late than never! Thank you. 🙂
