### ISSUE TITLE
Feature Request: Typescript Support

### ISSUE THREAD

**Issue by ryancraigmartin** [mattphillips/jest-expect-message#5]
**Feature Request: Typescript Support**

Description:

When attempting to run the example from the docs using TypeScript, I am still met with the following error.

**Example from docs:**
`    test(`returns 2 when adding 1 and 1`, () => {
        expect(1 + 1, `Woah this should be 2!`).toBe(2)
    })
Error: [ts] Expected 1 arguments, but got 2.
`

Changing it to a .js file allowed it to work, however, my project is TypeScript based and I was wondering if there are any plans to add TypeScript support for the package?

**Comment by drewxiuxiuxiu** [comment]
For those who want to get around with this: 
https://github.com/mattphillips/jest-expect-message/issues/1#issuecomment-457498948

**Comment by mike-d-davydov** [comment]
Implemented: https://www.npmjs.com/package/@types/jest-expect-message.
