### ISSUE TITLE
Extend eslint - jest/valid-expect - to allow 2nd optional argument for message.

### ISSUE THREAD

**Issue by alee8** [mattphillips/jest-expect-message#6]
**Feature Request**

Description: Add/modify eslint rule - `jest/valid-expect` - to allow for 2nd optional message argument/

Possible solution:
While the 2nd optional argument for message works. Eslint's `jest/valid-expect` rule fires unless disabled above.  Extend the current `jest/valid-expect` rule with additional value such as `allow-message`

**Comment by 0b10** [comment]
@alee8 did you find a way to just disable the linting for additional properties only? I couldn't find a way in either of the eslint/jest-plugin docs - I just set the rule to "off" for now.

**Comment by G-Rath** [comment]
@mattphillips this issue has been closed by https://github.com/jest-community/eslint-plugin-jest/pull/584
