### ISSUE TITLE
Incorrect set up instructions on npmjs.com/package/jest-expect-message#setup

### ISSUE THREAD

**Issue by ataylorme** [mattphillips/jest-expect-message#9]
**Bug**

- `package` version: `1.0.2`
- `node` version: `12.4.0`
- `npm` (or `yarn`) version: `6.9.0`

Relevant code or config

```json
"jest": {
  "setupTestFrameworkScriptFile": "jest-expect-message"
}
```

What you did:

Installed and configured `jest-expect-message` according to [the set up instructions on `npmjs.com`](https://www.npmjs.com/package/jest-expect-message#setup)

What happened:

Jest threw a deprecation warning about `setupTestFrameworkScriptFile`.

```
Deprecation Warning:

  Option "setupTestFrameworkScriptFile" was replaced by configuration "setupFilesAfterEnv", which supports multiple paths.

  Please update your configuration.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

**Comment by ataylorme** [comment]
I was able to resolve this quickly and [the README has the correct information](https://github.com/mattphillips/jest-expect-message/blob/master/README.md#setup) it is just the npm page that is out of date.

**Comment by mattphillips** [comment]
Thanks for noticing this, npm docs have been updated as of: https://www.npmjs.com/package/jest-expect-message/v/1.0.4
